### ISSUE TITLE
Runtime error occured

### ISSUE THREAD

**Issue by baba2580** [patheticGeek/torrent-aio-bot#11]
when i search Runtime error occured

2020-05-11T18:20:09.675307+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2020-05-11T18:20:09.675307+00:00 app[web.1]: 
2020-05-11T18:20:09.675308+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:750:14)
2020-05-11T18:20:09.675309+00:00 app[web.1]:     at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:739:50)
2020-05-11T18:20:09.675309+00:00 app[web.1]:     at Interface.emit (events.js:322:22)
2020-05-11T18:20:09.675309+00:00 app[web.1]:     at Interface.close (readline.js:409:8)
2020-05-11T18:20:09.675310+00:00 app[web.1]:     at Socket.onend (readline.js:187:10)
2020-05-11T18:20:09.675310+00:00 app[web.1]:     at Socket.emit (events.js:322:22)
2020-05-11T18:20:09.675311+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1187:12)
2020-05-11T18:20:09.675311+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-05-11T18:28:37.490127+00:00 heroku[router]: at=info method=GET path="/api/v1/search/1337x?query=windows%2010%20pro" host=abdur.herokuapp.com request_id=7ab314e0-bd94-4c87-9f56-e7f206937a63 fwd="91.109.28.129" dyno=web.1 connect=1ms service=24ms status=304 bytes=215 protocol=https
2020-05-11T18:28:37.489457+00:00 app[web.1]: Error: Failed to launch the browser process!
2020-05-11T18:28:37.489487+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
2020-05-11T18:28:37.489488+00:00 app[web.1]: 
2020-05-11T18:28:37.489488+00:00 app[web.1]: 
2020-05-11T18:28:37.489489+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2020-05-11T18:28:37.489490+00:00 app[web.1]: 
2020-05-11T18:28:37.489491+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/Launcher.js:750:14)
2020-05-11T18:28:37.489491+00:00 app[web.1]:     at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:739:50)
2020-05-11T18:28:37.489492+00:00 app[web.1]:     at Interface.emit (events.js:322:22)
2020-05-11T18:28:37.489492+00:00 app[web.1]:     at Interface.close (readline.js:409:8)
2020-05-11T18:28:37.489493+00:00 app[web.1]:     at Socket.onend (readline.js:187:10)
2020-05-11T18:28:37.489493+00:00 app[web.1]:     at Socket.emit (events.js:322:22)
2020-05-11T18:28:37.489494+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1187:12)
2020-05-11T18:28:37.489494+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by nexusdiscord** [comment]
Try deploying with git commit

**Comment by patheticGeek** [comment]
You need to add buildpack for puppetter. Heroku doestn have some libraries used by it.

How to add the buildpack:
Go to the build packs section in settings and click add buildpack and enter "https://github.com/jontewks/puppeteer-heroku-buildpack.git" as buildpack url then click save changes. And then do a dummy git commit so that heroku will buid it using the buildpack this time. Then set the SEARCH_SITE env to same value as SITE.

Let me know if its working

**Comment by baba2580** [comment]
![AS](https://user-images.githubusercontent.com/23245020/82128757-17bb3c00-97db-11ea-9efc-c0120bf11271.jpg)
![AA](https://user-images.githubusercontent.com/23245020/82128763-1e49b380-97db-11ea-95d8-a31265b318cf.jpg)

sir
i cant understand 
i have added build packs https://github.com/jontewks/puppeteer-heroku-buildpack.git
i am new sir 
please help step by step.
Request hai sir ji

**Comment by patheticGeek** [comment]
All you need to do is do an empty commit or change the readme file and commit it.
The build back is added when the project is next deployed inorder to do that youll have to do a commit

**Comment by baba2580** [comment]
How to change the readme file and commit it.

**Comment by patheticGeek** [comment]
Open your repo
Click on the readme.md file
Click on this pencil icon on top right
![edit1](https://user-images.githubusercontent.com/11344611/82129653-fc076400-97e1-11ea-8859-612d99f4b8ea.png)
Make any small change like add a space somewhere or delete a word etc.
Got down add a commit title
![edit2](https://user-images.githubusercontent.com/11344611/82129689-222d0400-97e2-11ea-9fa6-45cdeaca5158.png)
And click commit changes
This will start a build in heroku. Open your project in heroku and click on activity there you can see the status of build and wait for it to succeed and then try searching

**Comment by baba2580** [comment]
App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
       
 !     ERROR: Application not supported by 'heroku/nodejs' buildpack
 !     
 !     The 'heroku/nodejs' buildpack is set on this application, but was
 !     unable to detect a Node.js codebase.
 !         
 !     A Node.js app on Heroku requires a 'package.json' at the root of
 !     the directory structure.
 !     
 !     If you are trying to deploy a Node.js application, ensure that this
 !     file is present at the top level directory. This directory has the
 !     following files:
 !     
 !     README.md
 !         
 !     If you are trying to deploy an application written in another
 !     language, you need to change the list of buildpacks set on your
 !     Heroku app using the 'heroku buildpacks' command.
 !         
 !     For more information, refer to the following documentation:
 !     https://devcenter.heroku.com/articles/buildpacks
 !     https://devcenter.heroku.com/articles/nodejs-support#activation
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by patheticGeek** [comment]
Thats something i have never seen

**Comment by patheticGeek** [comment]
Just use search with mine as described in docs. set search site env to my site

**Comment by patheticGeek** [comment]
I'm gonna close this issue please update me on your situation
