### ISSUE TITLE
Telegram bot not working.

### ISSUE THREAD

**Issue by pctechkid** [patheticGeek/torrent-aio-bot#25]
No response from telegram bot eventhough bot token is configured. Here's the logs, might help.
```js
2020-06-02T07:17:08.639941+00:00 app[web.1]: Using api:  https://torrent-aio-bot.herokuapp.com/
2020-06-02T07:17:08.654627+00:00 app[web.1]: Bot ready
2020-06-02T07:17:08.674429+00:00 app[web.1]: > Running on http://localhost:38036
2020-06-02T07:17:08.675236+00:00 app[web.1]:
2020-06-02T07:17:08.675237+00:00 app[web.1]: Gdrive client up
2020-06-02T07:17:09.195355+00:00 heroku[web.1]: State changed from starting to up
2020-06-02T07:17:09.051370+00:00 app[web.1]: Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook: Failed to resolve host: Name or service not known
2020-06-02T07:17:09.051410+00:00 app[web.1]: at /app/node_modules/node-telegram-bot-api/src/telegram.js:283:15
2020-06-02T07:17:09.051411+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-06-02T07:17:09.051413+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-06-02T07:17:09.051419+00:00 app[web.1]: at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-06-02T07:17:09.051419+00:00 app[web.1]: at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-06-02T07:17:09.051420+00:00 app[web.1]: at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
2020-06-02T07:17:09.051420+00:00 app[web.1]: at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-06-02T07:17:09.051420+00:00 app[web.1]: at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-06-02T07:17:09.051421+00:00 app[web.1]: at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-06-02T07:17:09.051421+00:00 app[web.1]: at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-06-02T07:17:09.051422+00:00 app[web.1]: at processImmediate (internal/timers.js:456:21)
```

**Comment by patheticGeek** [comment]
did you set the SITE variable?

**Comment by pctechkid** [comment]
> did you set the SITE variable?

Yes, i set the value to my herokuapp site.

**Comment by pctechkid** [comment]
I found the cause of the issue just now. I tried putting '/' at the end of the site value just like the SEARCH_SITE var and it worked fine.
