### ISSUE TITLE
Heroku crashes every after torrent finished

### ISSUE THREAD

**Issue by pctechkid** [patheticGeek/torrent-aio-bot#27]
Logs:
```js
2020-06-02T10:24:02.839217+00:00 app[web.1]: events.js:292
2020-06-02T10:24:02.839226+00:00 app[web.1]: throw er; // Unhandled 'error' event
2020-06-02T10:24:02.839227+00:00 app[web.1]: ^
2020-06-02T10:24:02.839227+00:00 app[web.1]:
2020-06-02T10:24:02.839228+00:00 app[web.1]: Error: ENOTDIR invalid cwd /app/downloads/15f41c3a664e43184de2cb8563dcf0ba69fe5ac1/[Erai-raws] Princess Connect! Re-Dive - 09 [1080p][Multiple Subtitle].mkv
2020-06-02T10:24:02.839230+00:00 app[web.1]: at Glob._readdirError (/app/node_modules/glob/glob.js:592:21)
2020-06-02T10:24:02.839230+00:00 app[web.1]: at /app/node_modules/glob/glob.js:553:12
2020-06-02T10:24:02.839231+00:00 app[web.1]: at FSReqCallback.oncomplete (fs.js:155:23)
2020-06-02T10:24:02.839231+00:00 app[web.1]: Emitted 'error' event on Archiver instance at:
2020-06-02T10:24:02.839232+00:00 app[web.1]: at Archiver.onerror (/app/node_modules/readable-stream/lib/_stream_readable.js:640:52)
2020-06-02T10:24:02.839233+00:00 app[web.1]: at Archiver.emit (events.js:315:20)
2020-06-02T10:24:02.839233+00:00 app[web.1]: at Archiver.onGlobError (/app/node_modules/archiver/lib/core.js:636:10)
2020-06-02T10:24:02.839233+00:00 app[web.1]: at Glob.emit (events.js:315:20)
2020-06-02T10:24:02.839234+00:00 app[web.1]: at Glob._readdirError (/app/node_modules/glob/glob.js:595:14)
2020-06-02T10:24:02.839234+00:00 app[web.1]: at /app/node_modules/glob/glob.js:553:12
2020-06-02T10:24:02.839235+00:00 app[web.1]: at FSReqCallback.oncomplete (fs.js:155:23) {
2020-06-02T10:24:02.839236+00:00 app[web.1]: path: '/app/downloads/15f41c3a664e43184de2cb8563dcf0ba69fe5ac1/[Erai-raws] Princess Connect! Re-Dive - 09 [1080p][Multiple Subtitle].mkv',
2020-06-02T10:24:02.839237+00:00 app[web.1]: code: 'ENOTDIR'
2020-06-02T10:24:02.839238+00:00 app[web.1]: }
2020-06-02T10:24:03.118535+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-06-02T10:24:03.120734+00:00 app[web.1]: npm ERR! errno 1
2020-06-02T10:24:03.128865+00:00 app[web.1]: npm ERR! torrent-bot@1.0.0 start: `NODE_ENV=production node index.js`
2020-06-02T10:24:03.129514+00:00 app[web.1]: npm ERR! Exit status 1
2020-06-02T10:24:03.130126+00:00 app[web.1]: npm ERR!
2020-06-02T10:24:03.130669+00:00 app[web.1]: npm ERR! Failed at the torrent-bot@1.0.0 start script.
2020-06-02T10:24:03.131037+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-06-02T10:24:03.241402+00:00 app[web.1]:
2020-06-02T10:24:03.241757+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-06-02T10:24:03.241946+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-06-02T10_24_03_170Z-debug.log
2020-06-02T10:24:03.402446+00:00 heroku[web.1]: Process exited with status 1
2020-06-02T10:24:03.476745+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by sam23-dot** [comment]
keep that cont.. running with kaffine.heroku

**Comment by pctechkid** [comment]
> keep that cont.. running with kaffine.heroku

No, the issue isn't about that. It's about crash on the heroku app itself not the free dyno hours reset of heroku.

**Comment by patheticGeek** [comment]
> keep that cont.. running with kaffine.heroku

You dont have to use that, when you add the SITE variable i already have a bot that your server will register to and it'll ping your server every 30 mins. thats why the site variable is important

**Comment by patheticGeek** [comment]
> > keep that cont.. running with kaffine.heroku
> 
> No, the issue isn't about that. It's about crash on the heroku app itself not the free dyno hours reset of heroku.

Can vou provide the magnet link of file youre downloading?

**Comment by pctechkid** [comment]
> > > keep that cont.. running with kaffine.heroku
> > 
> > 
> > No, the issue isn't about that. It's about crash on the heroku app itself not the free dyno hours reset of heroku.
> 
> Can vou provide the magnet link of file youre downloading?

```js
magnet:?xt=urn:btih:CX2BYOTGJZBRQTPCZOCWHXHQXJU74WWB&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&dn=%5BErai-raws%5D%20Princess%20Connect%21%20Re-Dive%20-%2009%20%5B1080p%5D%5BMultiple%20Subtitle%5D.mkv
```

**Comment by patheticGeek** [comment]
The file can be downloaded and is uploaded to drive on my bot. So i'll be closing this issue

**Comment by pctechkid** [comment]
The issue has been resolved and confirmed. Thanks!
