### ISSUE TITLE
Telegram bot not working 

### ISSUE THREAD

**Issue by dstar22** [patheticGeek/torrent-aio-bot#37]
Log 

2020-06-15T12:10:23.248361+00:00 app[web.1]: Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook: Failed to resolve host: Name or service not known
2020-06-15T12:10:23.248371+00:00 app[web.1]:     at /app/node_modules/node-telegram-bot-api/src/telegram.js:283:15
2020-06-15T12:10:23.248372+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-06-15T12:10:23.248373+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-06-15T12:10:23.248373+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-06-15T12:10:23.248374+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-06-15T12:10:23.248374+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
2020-06-15T12:10:23.248375+00:00 app[web.1]:     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-06-15T12:10:23.248375+00:00 app[web.1]:     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-06-15T12:10:23.248375+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-06-15T12:10:23.248376+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-06-15T12:10:23.248377+00:00 app[web.1]:     at processImmediate (internal/timers.js:456:21)

**Comment by patheticGeek** [comment]
Did you set the telegram token correctly? and send the logs after restarting the process, does it says "Bot ready" ?

**Comment by dstar22** [comment]
Yes bro i set token correct TELEGRAM_TOKEN and value generated by botfather and then did restart all dyno then i pasted the log here and when i type command /start nothing works in telegram

**Comment by patheticGeek** [comment]
No i mean when you restart the dyno, the logs from its starting, if your token is correct it will show "Bot ready" in the logs

**Comment by dstar22** [comment]
> No I mean when you restart the dyno, the logs from its starting, if your token is correct it will show "Bot ready" in the logs

bro I deployed today again and it is working really awesome I really appreciate your hard work thank you so much, brother
