### ISSUE TITLE
Bot Not Working

### ISSUE THREAD

**Issue by theRay1s** [patheticGeek/torrent-aio-bot#39]
Do I need to disable Web 
To get Telegram Bot Working

**Comment by theRay1s** [comment]
]: Restarting
2020-06-22T03:50:24.141151+00:00 heroku[web.1]: State changed from up to starting
2020-06-22T03:50:25.412545+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-06-22T03:50:25.550685+00:00 heroku[web.1]: Process exited with status 143
2020-06-22T03:50:51.660887+00:00 heroku[web.1]: Starting process with command `npm start`
2020-06-22T03:50:54.174146+00:00 app[web.1]: 
2020-06-22T03:50:54.174161+00:00 app[web.1]: > torrent-bot@1.0.0 start /app
2020-06-22T03:50:54.174161+00:00 app[web.1]: > NODE_ENV=production node index.js
2020-06-22T03:50:54.174162+00:00 app[web.1]: 
2020-06-22T03:50:54.950342+00:00 app[web.1]: 
2020-06-22T03:50:54.950385+00:00 app[web.1]: GDRIVE_PARENT_FOLDER set to 0AE9bdn0g8VGhUk9P 
2020-06-22T03:50:55.450355+00:00 app[web.1]: Mon, 22 Jun 2020 03:50:55 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
2020-06-22T03:50:55.450372+00:00 app[web.1]: In the future, you will have to enable it yourself.
2020-06-22T03:50:55.450373+00:00 app[web.1]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:1138:30
2020-06-22T03:50:56.055619+00:00 heroku[web.1]: State changed from starting to up
2020-06-22T03:50:55.865892+00:00 app[web.1]: Using api:  https://seedrbot.herokuapp.com
2020-06-22T03:50:55.881789+00:00 app[web.1]: Bot ready
2020-06-22T03:50:55.885903+00:00 app[web.1]: web allowed
2020-06-22T03:50:55.910657+00:00 app[web.1]: > Running on http://localhost:47762
2020-06-22T03:50:55.911340+00:00 app[web.1]: 
2020-06-22T03:50:55.911341+00:00 app[web.1]: Gdrive client up 
2020-06-22T03:50:56.254531+00:00 app[web.1]: Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook: Failed to resolve host: Name or service not known
2020-06-22T03:50:56.254551+00:00 app[web.1]:     at /app/node_modules/node-telegram-bot-api/src/telegram.js:283:15
2020-06-22T03:50:56.254551+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-06-22T03:50:56.254552+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-06-22T03:50:56.254552+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-06-22T03:50:56.254553+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-06-22T03:50:56.254553+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
2020-06-22T03:50:56.254554+00:00 app[web.1]:     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-06-22T03:50:56.254554+00:00 app[web.1]:     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-06-22T03:50:56.254554+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-06-22T03:50:56.254555+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-06-22T03:50:56.254556+00:00 app[web.1]:     at processImmediate (internal/timers.js:456:21)

**Comment by theRay1s** [comment]
Found the error issue resolved

Thanks

**Comment by theRay1s** [comment]
But I have a request 
Bring Support for downloading URL

**Comment by patheticGeek** [comment]
> But I have a request
> Bring Support for downloading URL

I'm trying to make a new bot using aria2, webtorrent which i used here is giving some errors and crashing. Everything will come soon
