### ISSUE TITLE
Telegram Issue

### ISSUE THREAD

**Issue by Vardaan6189** [patheticGeek/torrent-aio-bot#40]
I got the bot on the telegram but the bot is not responding.... I am sending the magnet link and then reply the magnet link by "/download" command but then there is no response from the bot. If i am doing anything wrong Please can you guide me ......

Help would be appreciated this is my first  bot that i made on telegram

**Comment by patheticGeek** [comment]
Did you check the logs does it give any errors related to telegram?

**Comment by Vardaan6189** [comment]
Nope i didn't

**Comment by none5969** [comment]
Bro when will u release the new aria 2

**Comment by Vardaan6189** [comment]
> Did you check the logs does it give any errors related to telegram?

Well how can i check the logs 😅

**Comment by Vardaan6189** [comment]
And can you tell me the commands for the bot They are bit confusing

Thanks for helping a noob

**Comment by patheticGeek** [comment]
> And can you tell me the commands for the bot They are bit confusing
> 
> Thanks for helping a noob

send `/start` to the bot and it will send a message detailing all the commands

**Comment by patheticGeek** [comment]
> > Did you check the logs does it give any errors related to telegram?
> 
> Well how can i check the logs

Open the project in heroku click View More > logs

**Comment by patheticGeek** [comment]
> Bro when will u release the new aria 2

I'm working on it

**Comment by AkshitLala911** [comment]
Man same here I can't use the telegram , checked the logs nothing came , deployed the bot twice still telegram bot issue is there.

**Comment by Vardaan6189** [comment]
Well i checked the logs. Here is the screenshot link... Eell there is some telegram error 

Here is the link :-
 
 https://imgur.com/a/lZ2Ep1W

**Comment by Vardaan6189** [comment]
Here is the screenshot for the logs 

Logs:- https://imgur.com/a/EPcL5Kq

Config vars :- https://imgur.com/a/XNzVDIm

**Comment by patheticGeek** [comment]
open the logs click on the More then restart all dynos .. click on the save logs and upload that file here..

**Comment by patheticGeek** [comment]
if theres an error it will say so in starting otherwise it just says "bot up"

**Comment by f0rx4** [comment]
> if theres an error it will say so in starting otherwise it just says "bot up"

I got logs says "bot ready" but didn't get response in telegram

**Comment by patheticGeek** [comment]
> Bro when will u release the new aria 2

i might not heroku is banning it ive tried deploying a demo and account was suspended

**Comment by patheticGeek** [comment]
> [torrentrouzo-logs-1593272293320.txt](https://github.com/patheticGeek/torrent-aio-bot/files/4840810/torrentrouzo-logs-1593272293320.txt)
> 
> > if theres an error it will say so in starting otherwise it just says "bot up"
> 
> I got logs says "bot ready" but didn't get response in telegram

send another message .. i had people having this problem but it was resolved nobody has tol why this happened or the solution, might be that the token is wrong

**Comment by mangpa444** [comment]
I got the same problem.
I think the bot is getting blocked by heroku.
My bot dont reply to any thing i say or command.
`<a href="https://ibb.co/0XH5RsN"><img src="https://i.ibb.co/6ZjQ7Xh/Telegram-Web.png" alt="Telegram-Web" border="0"></a>`

**Comment by mangpa444** [comment]
I got the same problem.
I think the bot is getting blocked by heroku.
My bot dont reply to any thing i say or command.
[https://ibb.co/0XH5RsN](url)

**Comment by patheticGeek** [comment]
> I got the same problem.
> I think the bot is getting blocked by heroku.
> My bot dont reply to any thing i say or command.
> [https://ibb.co/0XH5RsN](url)

This bot is not yet flagged by heroku so it is not being blocked. Please attach heroku logs.

**Comment by dstar22** [comment]
I was having the same issue make a new bot everytime u deploy dont use the same bot for other try it fixed mine but telegram bot has few bugs

**Comment by nimma0001** [comment]
https://pastebin.com/wrBAS195[File.txt](https://pastebin.com/dl/wrBAS195) 
 Error etelegram 400eroor

**Comment by patheticGeek** [comment]
Some more people have gotten this error but was fixed in some time i am unable to reproduce this error

**Comment by aritradatta0** [comment]
This the error i'm getting

2020-10-03T13:57:04.459103+00:00 app[web.1]: Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook: Failed to resolve host: Name or service not known
2020-10-03T13:57:04.459117+00:00 app[web.1]:     at /app/node_modules/node-telegram-bot-api/src/telegram.js:283:15
2020-10-03T13:57:04.459117+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-10-03T13:57:04.459118+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-10-03T13:57:04.459119+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-10-03T13:57:04.459119+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-10-03T13:57:04.459120+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
2020-10-03T13:57:04.459120+00:00 app[web.1]:     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-10-03T13:57:04.459120+00:00 app[web.1]:     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-10-03T13:57:04.459122+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-10-03T13:57:04.459123+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-10-03T13:57:04.459123+00:00 app[web.1]:     at processImmediate (internal/timers.js:456:21)

**Comment by opeth1990** [comment]
SITE config setting to add  /  at the end.
