### ISSUE TITLE
Not uploading to Gdrive

### ISSUE THREAD

**Issue by himate143** [patheticGeek/torrent-aio-bot#7]
i have kept  client id,secret,auth code,token,gdrive, telegram token parent but file is not getting uploaded at gdrive....im only getting heroku download link in bot..posting log please help i am very new to these.Thank You

2020-03-27T20:17:01.793050+00:00 heroku[router]: at=info method=POST path="/api/v1/torrent/bot" host=jj.herokuapp.com request_id=177fd8f6-34d0-4b4b-ab44-bbcc3cfd02fd fwd="91.108.6.70" dyno=web.1 connect=0ms service=27ms status=200 bytes=224 protocol=https
2020-03-27T20:18:53.918696+00:00 app[web.1]: Uploading folder to gdrive: Big Buck Bunny
2020-03-27T20:18:54.023050+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Error: File not found: https://drive.google.com/drive/u/1/folders/1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ.
2020-03-27T20:18:54.023053+00:00 app[web.1]:     at Gaxios.<anonymous> (/app/node_modules/gaxios/build/src/gaxios.js:73:27)
2020-03-27T20:18:54.023054+00:00 app[web.1]:     at Generator.next (<anonymous>)
2020-03-27T20:18:54.023054+00:00 app[web.1]:     at fulfilled (/app/node_modules/gaxios/build/src/gaxios.js:16:58)
2020-03-27T20:18:54.023055+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2020-03-27T20:18:54.023056+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-03-27T20:18:54.023112+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-03-27T20:18:54.023142+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by patheticGeek** [comment]
Open the heroku download link there will be a gdrive.txt file in there it shows the gdrive progress. I'm still working on adding support to show gdrive links directly in msg and on site

**Comment by himate143** [comment]
> Open the heroku download link there will be a gdrive.txt file in there it shows the gdrive progress. I'm still working on adding support to show gdrive links directly in msg and on site
> Can you confirm if there's a gdrive link in the txt file or the folder shows in gdrive?

it just shows upload started in that text file named gdrive but its not getting uploaded so i seen logs and posted..

**Comment by patheticGeek** [comment]
do the bot have access to account from which you created folder from?
If you an deploy it again that will be helpful, sorry for responses like this :-(
it happened once with me then it worked on 2nd try and don't have any problem. Haven't been able to reproduce it. 
I'm new to making projects like this for people to use so don't have much experience debugging things like this. will keep the issue open so if anyone else has same problem they can comment here with steps to reproduce

**Comment by himate143** [comment]
> do the bot have access to account from which you created folder from?
> If you an deploy it again that will be helpful, sorry for responses like this :-(
> it happened once with me then it worked on 2nd try and don't have any problem. Haven't been able to reproduce it.
> I'm new to making projects like this for people to use so don't have much experience debugging things like this. will keep the issue open so if anyone else has same problem they can comment here with steps to reproduce

how to give bot access to account from  which i created folder? i followed readme and did if its not in readme i could have missed it..now when i tried again torrent is not downloading(big buck bunny) and other at all before it downloads n gave heroku links..i know you will figure it out n fix it soon :).. Thanks

**Comment by patheticGeek** [comment]
when you sign in with the link copies from logs that account is same as in which you created the folder whose id you put in ? Have you tried any other torrent does it work?
i have asked for permission to view  https://drive.google.com/drive/u/1/folders/1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ it was in logs can you provide it?

**Comment by himate143** [comment]
> when you sign in with the link copies from logs that account is same as in which you created the folder whose id you put in ? Have you tried any other torrent does it work?
> i have asked for permission to view https://drive.google.com/drive/u/1/folders/1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ it was in logs can you provide it?

yes i only used 1 account for all these and that link i made it private later on..i will once try again now with  torrents and update

**Comment by patheticGeek** [comment]
Just relaesed it. youre maybe putting the folder url in there and not the folder id.
set GDRIVE_PARENT_FOLDER to "1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ" without quotes

**Comment by himate143** [comment]
> Just relaesed it. youre maybe putting the folder url in there and not the folder id.
> set GDRIVE_PARENT_FOLDER to "1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ" without quotes

ok will trt now

**Comment by himate143** [comment]
> Just relaesed it. youre maybe putting the folder url in there and not the folder id.
> set GDRIVE_PARENT_FOLDER to "1BC4TYce-O07UwcfyS7xg94stAmo6mKkZ" without quotes

its fine now ..thanks alot..but one issue how to know progress in bot after keeping Torrent? it automatically tells that Torrent is completed after sometime ..

**Comment by patheticGeek** [comment]
Noice. on website in downloads section it will show the progress. still working on adding the gdrive progress. On telegram there is a command send /start to see that. I'm new to telegram api will add auto updating message support soon. the torrent started by telegram bot can be seen on the site it will show the progress there
