### ISSUE TITLE
File Not Uploading to gdrive and folders in heroku are empty?

### ISSUE THREAD

**Issue by phantom2152** [patheticGeek/torrent-aio-bot#95]
logs after giving an torrent

```
2021-03-26T07:48:55.165108+00:00 app[web.1]: Gdrive client up 
2021-03-26T07:48:55.521111+00:00 heroku[web.1]: State changed from starting to up
2021-03-26T07:49:11.934007+00:00 heroku[router]: at=info method=GET path="/" host=tor-drive.herokuapp.com request_id=d3d666f2-bbd8-452c-ab05-aa6460e0b156 fwd="157.45.245.76" dyno=web.1 connect=0ms service=61ms status=304 bytes=302 protocol=https
2021-03-26T07:49:12.532530+00:00 heroku[router]: at=info method=GET path="/static/css/main.1bd3c108.chunk.css" host=tor-drive.herokuapp.com request_id=e3334008-2abd-4052-aedc-51accf63b3ad fwd="157.45.245.76" dyno=web.1 connect=0ms service=4ms status=304 bytes=303 protocol=https
2021-03-26T07:49:12.842069+00:00 heroku[router]: at=info method=GET path="/static/js/3.0a6f9a57.chunk.js" host=tor-drive.herokuapp.com request_id=0835f6dd-10cf-4728-9d08-a8ba5d57cae2 fwd="157.45.245.76" dyno=web.1 connect=0ms service=7ms status=304 bytes=304 protocol=https
2021-03-26T07:49:13.366872+00:00 heroku[router]: at=info method=GET path="/static/js/main.017b3f99.chunk.js" host=tor-drive.herokuapp.com request_id=bb5528d6-5e7a-45ea-8c57-678bd033c265 fwd="157.45.245.76" dyno=web.1 connect=1ms service=9ms status=304 bytes=303 protocol=https
2021-03-26T07:49:14.183396+00:00 heroku[router]: at=info method=GET path="/static/js/6.7b4a97a9.chunk.js" host=tor-drive.herokuapp.com request_id=11b6d4a4-2612-4aa1-bb05-a896f0a97aaa fwd="157.45.245.76" dyno=web.1 connect=1ms service=3ms status=304 bytes=303 protocol=https
2021-03-26T07:49:14.553751+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=804b2322-9435-4aac-ab31-579af2626924 fwd="157.45.245.76" dyno=web.1 connect=1ms service=5ms status=304 bytes=302 protocol=https
2021-03-26T07:49:15.579941+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=99b16b38-3b63-450c-95a6-9d1ebb3ec865 fwd="157.45.245.76" dyno=web.1 connect=0ms service=3ms status=304 bytes=302 protocol=https
2021-03-26T07:49:15.574190+00:00 heroku[router]: at=info method=GET path="/static/js/4.92b2d0b5.chunk.js" host=tor-drive.herokuapp.com request_id=60269ab1-1966-4f5b-afe1-3b9ca0f7fb51 fwd="157.45.245.76" dyno=web.1 connect=0ms service=12ms status=304 bytes=302 protocol=https
2021-03-26T07:49:15.567415+00:00 heroku[router]: at=info method=GET path="/static/js/0.623cfa0a.chunk.js" host=tor-drive.herokuapp.com request_id=c1e06ada-f274-47d4-8094-168e3bf675e0 fwd="157.45.245.76" dyno=web.1 connect=1ms service=25ms status=304 bytes=303 protocol=https
2021-03-26T07:49:16.123617+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=da3c6e98-e702-404d-af94-5ed880a4896d fwd="157.45.245.76" dyno=web.1 connect=1ms service=6ms status=304 bytes=215 protocol=https
2021-03-26T07:49:18.072295+00:00 heroku[router]: at=info method=GET path="/static/js/5.10800f32.chunk.js" host=tor-drive.herokuapp.com request_id=058a65a4-36b0-4da4-a1ef-ff9e329f9287 fwd="157.45.245.76" dyno=web.1 connect=1ms service=3ms status=304 bytes=302 protocol=https
2021-03-26T07:49:18.087979+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=3613f8b3-621b-41e2-a466-0bbc7bca0a5c fwd="157.45.245.76" dyno=web.1 connect=0ms service=3ms status=304 bytes=302 protocol=https
2021-03-26T07:49:18.599973+00:00 heroku[router]: at=info method=GET path="/api/v1/drive/folder?id=" host=tor-drive.herokuapp.com request_id=a3603331-c264-4366-8d3d-e339fc1ec0ae fwd="157.45.245.76" dyno=web.1 connect=0ms service=174ms status=304 bytes=214 protocol=https
2021-03-26T07:49:22.291337+00:00 heroku[router]: at=info method=GET path="/drive" host=tor-drive.herokuapp.com request_id=4baa3fdb-dd59-4622-8418-116ab266a46a fwd="157.45.245.76" dyno=web.1 connect=0ms service=5ms status=304 bytes=302 protocol=https
2021-03-26T07:49:22.773776+00:00 heroku[router]: at=info method=GET path="/static/js/3.0a6f9a57.chunk.js" host=tor-drive.herokuapp.com request_id=f8298870-c86b-4f95-94b0-12e6c07d0f14 fwd="157.45.245.76" dyno=web.1 connect=2ms service=8ms status=304 bytes=304 protocol=https
2021-03-26T07:49:22.785537+00:00 heroku[router]: at=info method=GET path="/static/js/main.017b3f99.chunk.js" host=tor-drive.herokuapp.com request_id=77ec4d64-5b98-4fbc-a5fd-f66e39092454 fwd="157.45.245.76" dyno=web.1 connect=0ms service=3ms status=304 bytes=303 protocol=https
2021-03-26T07:49:22.755879+00:00 heroku[router]: at=info method=GET path="/static/css/main.1bd3c108.chunk.css" host=tor-drive.herokuapp.com request_id=ce251aa6-6d64-43a2-81d8-c4b9c0f977d1 fwd="157.45.245.76" dyno=web.1 connect=0ms service=2ms status=304 bytes=303 protocol=https
2021-03-26T07:49:23.195998+00:00 heroku[router]: at=info method=GET path="/static/js/0.623cfa0a.chunk.js" host=tor-drive.herokuapp.com request_id=30d764b0-a7f4-4ea1-ac33-82e5af953536 fwd="157.45.245.76" dyno=web.1 connect=1ms service=16ms status=304 bytes=303 protocol=https
2021-03-26T07:49:23.202686+00:00 heroku[router]: at=info method=GET path="/static/js/5.10800f32.chunk.js" host=tor-drive.herokuapp.com request_id=8cc57263-25b6-498b-9109-95d9b7ae443e fwd="157.45.245.76" dyno=web.1 connect=1ms service=5ms status=304 bytes=302 protocol=https
2021-03-26T07:49:23.600066+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=143c14f1-0ce7-418b-9f30-beabfe6a8cba fwd="157.45.245.76" dyno=web.1 connect=1ms service=19ms status=200 bytes=2003 protocol=https
2021-03-26T07:49:24.793431+00:00 heroku[router]: at=info method=GET path="/api/v1/drive/folder?id=" host=tor-drive.herokuapp.com request_id=8df65aa7-7984-46a8-923c-e4c4a41dc856 fwd="157.45.245.76" dyno=web.1 connect=1ms service=1251ms status=304 bytes=214 protocol=https
2021-03-26T07:49:25.079725+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=0aadb702-a218-471a-b533-1034d488dcec fwd="157.45.245.76" dyno=web.1 connect=0ms service=3ms status=304 bytes=302 protocol=https
2021-03-26T07:49:25.033402+00:00 heroku[router]: at=info method=GET path="/static/js/4.92b2d0b5.chunk.js" host=tor-drive.herokuapp.com request_id=dc87fd2b-ddef-4378-9b00-afad0f6cadd0 fwd="157.45.245.76" dyno=web.1 connect=0ms service=2ms status=304 bytes=302 protocol=https
2021-03-26T07:49:25.617030+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=2e3f5093-9ac4-4410-979c-9ab75ec8824d fwd="157.45.245.76" dyno=web.1 connect=0ms service=6ms status=304 bytes=215 protocol=https
2021-03-26T07:49:29.078082+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=a424d01c-4855-44fe-ae83-05fc7b07471f fwd="157.45.245.76" dyno=web.1 connect=1ms service=7ms status=304 bytes=215 protocol=https
2021-03-26T07:49:32.276529+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/download?link=magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny" host=tor-drive.herokuapp.com request_id=b3ea6984-d4ef-470c-8105-d6aab388625b fwd="157.45.245.76" dyno=web.1 connect=2ms service=1379ms status=304 bytes=215 protocol=https
2021-03-26T07:49:32.876376+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=efd683cc-df81-4fe1-ab05-5934d488e828 fwd="157.45.245.76" dyno=web.1 connect=0ms service=9ms status=200 bytes=664 protocol=https
2021-03-26T07:49:34.742567+00:00 heroku[router]: at=info method=GET path="/static/js/6.7b4a97a9.chunk.js" host=tor-drive.herokuapp.com request_id=d98da52d-497e-4dee-b661-84802bff4ae9 fwd="157.45.245.76" dyno=web.1 connect=0ms service=27ms status=304 bytes=303 protocol=https
2021-03-26T07:49:34.719992+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=357b514d-b1f4-4f06-840e-15924bfc209f fwd="157.45.245.76" dyno=web.1 connect=0ms service=11ms status=304 bytes=302 protocol=https
2021-03-26T07:49:36.902763+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=3321bee3-9888-48a5-ab26-b2e780ccf055 fwd="157.45.245.76" dyno=web.1 connect=1ms service=34ms status=200 bytes=711 protocol=https
2021-03-26T07:49:36.982938+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=tor-drive.herokuapp.com request_id=13143b0f-7a36-4c7b-9bf8-36891fe3bbf4 fwd="157.45.245.76" dyno=web.1 connect=0ms service=33ms status=304 bytes=302 protocol=https
2021-03-26T07:49:40.479967+00:00 heroku[router]: at=info method=GET path="/api/v1/torrent/list" host=tor-drive.herokuapp.com request_id=01df7a30-5b37-48ad-a47f-256442a29b54 fwd="157.45.245.76" dyno=web.1 connect=1ms service=85ms status=200 bytes=712 protocol=https
2021-03-26T07:51:00.181433+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
2021-03-26T07:51:00.181457+00:00 app[web.1]:     at Object.writeFileSync (fs.js:1460:5)
2021-03-26T07:51:00.181457+00:00 app[web.1]:     at mkfile (/app/utils/mkfile.js:17:6)
2021-03-26T07:51:00.181459+00:00 app[web.1]:     at /app/lib/torrent.js:79:7
2021-03-26T07:51:00.181459+00:00 app[web.1]:     at Array.forEach (<anonymous>)
2021-03-26T07:51:00.181460+00:00 app[web.1]:     at Torrent.saveFiles (/app/lib/torrent.js:75:19)
2021-03-26T07:51:00.181461+00:00 app[web.1]:     at Torrent.<anonymous> (/app/lib/torrent.js:47:14)
2021-03-26T07:51:00.181461+00:00 app[web.1]:     at Object.onceWrapper (events.js:421:28)
2021-03-26T07:51:00.181462+00:00 app[web.1]:     at Torrent.emit (events.js:315:20)
2021-03-26T07:51:00.181463+00:00 app[web.1]:     at Torrent._checkDone (/app/node_modules/webtorrent/lib/torrent.js:1585:12)
2021-03-26T07:51:00.181463+00:00 app[web.1]:     at /app/node_modules/webtorrent/lib/torrent.js:1539:20
2021-03-26T07:51:00.181464+00:00 app[web.1]:     at /app/node_modules/simple-sha1/index.js:6:5
2021-03-26T07:51:00.181464+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:75:11)
2021-03-26T07:51:00.181465+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-03-26T07:51:00.181526+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-03-26T07:51:00.181635+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by phantom2152** [comment]
Hey the issue is solved , Inorder to fix this issue you can merge this pull request 58bb9d0
